/*
	SQLSTUDIOADVANCEDAdvancedExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface SQLSTUDIOADVANCEDAdvancedExample : NSObject {
}
-(void)run;
@end
		